### ISSUE TITLE
couldn't connect to any seeds module=p2p

### ISSUE THREAD

**Issue by freshman-db** [ovrclk/akash-testnet-3#2]
I am running a akash node on testnet,but couldn't connect to any seeds module=p2p
![image](https://user-images.githubusercontent.com/13075728/157318283-2518101f-1eb5-45dd-92d9-93f3f63cc654.png)

**Comment by boz** [comment]
hi @acode-eth - what do you have for `persistent_peers` and `seeds` in `config.toml`?

**Comment by freshman-db** [comment]
Remove the first peer address from config file.
Fixed.
