### ISSUE TITLE
Misbehave spend issue

### ISSUE THREAD

**Issue by chaudharypraveen98** [ovrclk/akash-testnet-3#5]
I am trying to send the token from one wallet to another using a secondary account for payment. So instead of failing, it is executing.

Issue confirmed by mando-Akash

Input command : akash tx bank send $AKASH_KEY_NAME akash17ck7uhkpjjj45fw9s9vpv7jn0m97958vjjxmf8 1000uakt --from $AKASH_ACCOUNT_ADDRESS1 --gas-prices="0.025uakt" --gas="auto" --gas-adjustment=1.5 -y

Ouput : 
{
	"height":"788750",
	"txhash":"41BCAD3028C9AF947C3AC0AF0D785748300F408CEAED361771B8F36CDAF09989",
	"codespace":"",
	"code":0,
	"data":"0A1E0A1C2F636F736D6F732E62616E6B2E763162657461312E4D736753656E64",
	"raw_log":"[{\"events\":[{\"type\":\"coin_received\",\"attributes\":[{\"key\":\"receiver\",\"value\":\"akash1h27tc050zd9pf8x6ecadh2h6g54sj32f47sryu\"},{\"key\":\"amount\",\"value\":\"1000uakt\"}]},{\"type\":\"coin_spent\",\"attributes\":[{\"key\":\"spender\",\"value\":\"akash150qcw48kgulv26hgdcwed2xs8fmjmj62qj7xr4\"},{\"key\":\"amount\",\"value\":\"1000uakt\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/cosmos.bank.v1beta1.MsgSend\"},{\"key\":\"sender\",\"value\":\"akash150qcw48kgulv26hgdcwed2xs8fmjmj62qj7xr4\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"akash1h27tc050zd9pf8x6ecadh2h6g54sj32f47sryu\"},{\"key\":\"sender\",\"value\":\"akash150qcw48kgulv26hgdcwed2xs8fmjmj62qj7xr4\"},{\"key\":\"amount\",\"value\":\"1000uakt\"}]}]}]",
	"logs":[
		{
			"msg_index":0,
			"log":"",
			"events":[
				{
					"type":"coin_received",
					"attributes":[
						{
							"key":"receiver",
							"value":"akash1h27tc050zd9pf8x6ecadh2h6g54sj32f47sryu"
						},
						{
							"key":"amount",
							"value":"1000uakt"
						}
					]
				},
				{
					"type":"coin_spent",
					"attributes":[
						{
							"key":"spender",
							"value":"akash150qcw48kgulv26hgdcwed2xs8fmjmj62qj7xr4"
						},
						{
							"key":"amount",
							"value":"1000uakt"
						}
					]
				},
				{
					"type":"message",
					"attributes":[
						{
							"key":"action",
							"value":"/cosmos.bank.v1beta1.MsgSend"
						},
						{
							"key":"sender",
							"value":"akash150qcw48kgulv26hgdcwed2xs8fmjmj62qj7xr4"
						},
						{
							"key":"module",
							"value":"bank"
						}
					]
				},
				{
					"type":"transfer",
					"attributes":[
						{
							"key":"recipient",
							"value":"akash1h27tc050zd9pf8x6ecadh2h6g54sj32f47sryu"
						},
						{
							"key":"sender",
							"value":"akash150qcw48kgulv26hgdcwed2xs8fmjmj62qj7xr4"
						},
						{
							"key":"amount",
							"value":"1000uakt"
						}
					]
				}
			]
		}
	],
	"info":"",
	"gas_wanted":"88699",
	"gas_used":"68652",
	"tx":null,
	"timestamp":"",
	"events":[
		{
			"type":"coin_spent",
			"attributes":[
				{
					"key":"c3BlbmRlcg==",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQ=",
					"index":true
				},
				{
					"key":"YW1vdW50",
					"value":"MjIxOHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"coin_received",
			"attributes":[
				{
					"key":"cmVjZWl2ZXI=",
					"value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=",
					"index":true
				},
				{
					"key":"YW1vdW50",
					"value":"MjIxOHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"transfer",
			"attributes":[
				{
					"key":"cmVjaXBpZW50",
					"value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=",
					"index":true
				},
				{
					"key":"c2VuZGVy",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQ=",
					"index":true
				},
				{
					"key":"YW1vdW50",
					"value":"MjIxOHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"message",
			"attributes":[
				{
					"key":"c2VuZGVy",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQ=",
					"index":true
				}
			]
		},
		{
			"type":"tx",
			"attributes":[
				{
					"key":"ZmVl",
					"value":"MjIxOHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"tx",
			"attributes":[
				{
					"key":"YWNjX3NlcQ==",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQvMTA=",
					"index":true
				}
			]
		},
		{
			"type":"tx",
			"attributes":[
				{
					"key":"c2lnbmF0dXJl",
					"value":"dk5YTjJZZXN3cmdvS0JtVi9jL1RZQkt4OURyM09idndNdDBqejZUeUlRUlM0T2dieFdDSjUwRGlvMlZTMTF1U3l4dnhpR3k0RFRxei9uZi95SFZHRWc9PQ==",
					"index":true
				}
			]
		},
		{
			"type":"message",
			"attributes":[
				{
					"key":"YWN0aW9u",
					"value":"L2Nvc21vcy5iYW5rLnYxYmV0YTEuTXNnU2VuZA==",
					"index":true
				}
			]
		},
		{
			"type":"coin_spent",
			"attributes":[
				{
					"key":"c3BlbmRlcg==",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQ=",
					"index":true
				},
				{
					"key":"YW1vdW50",
					"value":"MTAwMHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"coin_received",
			"attributes":[
				{
					"key":"cmVjZWl2ZXI=",
					"value":"YWthc2gxaDI3dGMwNTB6ZDlwZjh4NmVjYWRoMmg2ZzU0c2ozMmY0N3NyeXU=",
					"index":true
				},
				{
					"key":"YW1vdW50",
					"value":"MTAwMHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"transfer",
			"attributes":[
				{
					"key":"cmVjaXBpZW50",
					"value":"YWthc2gxaDI3dGMwNTB6ZDlwZjh4NmVjYWRoMmg2ZzU0c2ozMmY0N3NyeXU=",
					"index":true
				},
				{
					"key":"c2VuZGVy",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQ=",
					"index":true
				},
				{
					"key":"YW1vdW50",
					"value":"MTAwMHVha3Q=",
					"index":true
				}
			]
		},
		{
			"type":"message",
			"attributes":[
				{
					"key":"c2VuZGVy",
					"value":"YWthc2gxNTBxY3c0OGtndWx2MjZoZ2Rjd2VkMnhzOGZtam1qNjJxajd4cjQ=",
					"index":true
				}
			]
		},
		{
			"type":"message",
			"attributes":[
				{
					"key":"bW9kdWxl",
					"value":"YmFuaw==",
					"index":true
				}
			]
		}
	]
}

![Screenshot from 2022-03-11 01-17-48](https://user-images.githubusercontent.com/43620425/157743014-5a5ae59f-2703-4059-b67d-5267a0fda805.png)

**Comment by AlaniAKT** [comment]
We are looking into this and will have an update for you shortly.

**Comment by AlaniAKT** [comment]
Hello, This is Authz related and the ability to authorize spend by proxy, in addition to what it can be used for. Per engineering feedback, you should not be able to send tokens to an arbitrary destination when authorized to spend on a deployment.
