### ISSUE TITLE
Change the amount of funding from grantee aacount

### ISSUE THREAD

**Issue by alfset** [ovrclk/akash-testnet-3#7]
I think i found some bug
Confirmed by mando-akash

It's posible to change the amount of funding amount from grante account
 1. First login with first wallet

AKASH_KEY_NAME=myWallet
export AKASH_ACCOUNT_ADDRESS="$(akash keys show $AKASH_KEY_NAME -a)"
echo $AKASH_ACCOUNT_ADDRESS

2. Make authz grant transaction

akash tx deployment authz grant akash10jner6syush9l27y08t49ydxuv40uchzqwcwgl 1000uakt --from akash1ct8epgddxx88azhs2shv3p07xk8nsuvm5sjadk --gas-prices="0.025uakt" --gas="auto" --gas-adjustment=1.5 -y

3. query it
akash query authz grants  akash1ct8epgddxx88azhs2shv3p07xk8nsuvm5sjadk akash10jner6syush9l27y08t49ydxuv40uchzqwcwgl

4. Switch to another wallet

AKASH_KEY_NAME=myWallet4
export AKASH_ACCOUNT_ADDRESS="$(akash keys show $AKASH_KEY_NAME -a)"
echo $AKASH_ACCOUNT_ADDRESS
akash10jner6syush9l27y08t49ydxuv40uchzqwcwgl

Query it

akash query authz grants akash1ct8epgddxx88azhs2shv3p07xk8nsuvm5sjadk akash10jner6syush9l27y08t49ydxuv40uchzqwcwgl 

grants:
- authorization:
    '@type': /akash.deployment.v1beta2.DepositDeploymentAuthorization
    spend_limit:
      amount: "1000"
      denom: uakt
  expiration: "[2023-03-11]

6.Change the amount with

akash tx deployment authz grant akash10jner6syush9l27y08t49ydxuv40uchzqwcwgl 5000uakt --from akash1ct8epgddxx88azhs2shv3p07xk8nsuvm5sjadk --gas-prices="0.025uakt" --gas="auto" --gas-adjustment=1.5 -y

{"height":"[801695](tel:801695)","txhash":"DA2C2D2EAF[6668629](tel:6668629)C19DE7823C311E799AC30CCA5AAAB490F15D2DDA008CE7F","codespace":"","code":0,"data":"0A200A1E2F636F736D6F732E[617574687](tel:617574687)A2E763162657461312E4D[73674772616](tel:73674772616)E74","raw_log":"[{\"events\":[{\"type\":\"cosmos.authz.v1beta1.EventGrant\",\"attributes\":[{\"key\":\"msg_type_url\",\"value\":\"\\\"

After susscesfull when you query it again the amount was change

akash query authz grants akash1ct8epgddxx88azhs2shv3p07xk8nsuvm5sjadk akash10jner6syush9l27y08t49ydxuv40uchzqwcwgl 

akash.deployment.v1beta2.DepositDeploymentAuthorization
    spend_limit:
      amount: "5000"
      denom: uakt
  expiration: "[2023-03-11](tel:20230311)T15:03:12Z"
pagination:
  next_key: null
  total: "0"

**Comment by AlaniAKT** [comment]
Looks like the grantor authorizing tokens to the grantee, and the grantee self-authorizing tokens. This is under review, update to follow shortly.

**Comment by alfset** [comment]
Any update about this issues?

**Comment by AlaniAKT** [comment]
This is not a bug - grantor authorizing tokens to the grantee, and the grantee self-authorizing tokens.
